
notifications:
  email:
    - peter.mechlenborg@gmail.com
    - ahj@trifork.com

language: node_js

node_js:
  - "0.10"

addons:
  postgresql: 9.3

env:
  - pgConnectionUrl=postgres://postgres@127.0.0.1:5432/dawaintegrationtest

before_script:
  - sudo locale-gen --no-archive da_DK.UTF-8
  - bash psql/createdb/createdb.bash localhost dawaintegrationtest postgres
  - node psql/setup-db.js
  - node psql/load-adresse-data.js --dataDir=test/data --format=bbr
  - psql -U travis dawatest < load-dagi-test-data.sql

