
notifications:
  email:
    - fij@mbbl.dk
    - anders@andershessellund.dk

language: node_js

node_js:
  - "4.2.1"

addons:
  postgresql: 9.4

env:
  - pgConnectionUrl=postgres://postgres@127.0.0.1:5432/dawaintegrationtest pgEmptyDbUrl=postgres://postgres@127.0.0.1:5432/dawaempty logConfiguration=travis-ci-client-logconfig.json

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.8
  - sudo locale-gen --no-archive da_DK.UTF-8

before_script:
  - bash psql/createdb/createdb.bash localhost dawaintegrationtest postgres
  - bash psql/createdb/createdb.bash localhost dawaempty postgres
  - pgConnectionUrl=postgres://postgres@127.0.0.1:5432/dawaintegrationtest node psql/loadTestData.js
  - pgConnectionUrl=postgres://postgres@127.0.0.1:5432/dawaempty node psql/setup-db.js
